services:
  database:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: event_manager
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root"]
      interval: 10s
      timeout: 5s
      retries: 5
    
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: event_manager_app
    ports:
      - "3000:3000"
    depends_on:
        - database
    command: >
      sh -c "
      npm run sequelize:migrate &&
      npm run sequelize:seed &&
      npm start
      "